version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - iga-network
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USER}", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql 

  backend:
    networks:
      - iga-network
    build: ./backend-nest
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

  frontend:
    networks:
      - iga-network
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  admin:
    networks:
      - iga-network
    build: ./backend-admin
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    environment:
      
      CI_ENVIRONMENT: development
      database_default_hostname: db
      database_default_database: ${DB_NAME}
      database_default_username: ${DB_USER}
      database_default_password: ${DB_PASSWORD}
      database_default_DBDriver: MySQLi

networks:
  iga-network:
    driver: bridge


volumes:
  mysql_data: